### PR TITLE
Collect more metadata for service offering

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/topological_inventory-collector-openshift/pull/9

### CODE REVIEW

**Comment by Ladas** [comment]
cc @agrare

**Comment by Ladas** [comment]
@slemrmartin more for mock collector

**Comment by agrare** [comment]
@Ladas does this need to be rebased?  I'm still seeing the collect tags commit

**Comment by agrare** [comment]
Nevermind it merged cleanly locally

**Pull request merged**
